# Generated by Django 5.2.14 on 2026-06-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_processor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='file',
        ),
        migrations.AddField(
            model_name='invoice',
            name='image_url',
            field=models.URLField(default='https://placeholder.example.com', max_length=2048),
            preserve_default=False,
        ),
    ]
